# Generated by Django 2.0.5 on 2018-06-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180611_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='menu',
            field=models.ManyToManyField(blank=True, null=True, to='crm.Menu', verbose_name='菜单'),
        ),
    ]
