# Generated by Django 2.0.5 on 2018-06-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20180611_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=32, verbose_name='菜单名'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url_name',
            field=models.CharField(max_length=64, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='role',
            name='menu',
            field=models.ManyToManyField(blank=True, to='crm.Menu', verbose_name='菜单'),
        ),
    ]
