# Generated by Django 2.0.5 on 2018-06-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20180619_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='class_type',
            field=models.SmallIntegerField(choices=[(0, '面授（脱产）'), (1, '面授（周末）'), (2, '网络班')], max_length=32, verbose_name='班级类型'),
        ),
    ]
